### ISSUE TITLE
Can't "npm install max7219" with current builds

### ISSUE THREAD

**Issue by nkolban** [victorporof/MAX7219.js#1]
I am running Raspbian Jessie on a Pi 2 ... when I try and execute "npm install max7219", it fails.

Here are some of the relevant details:

$ uname -a
Linux raspberrypi 4.1.15-v7+ #830 SMP Tue Dec 15 17:02:45 GMT 2015 armv7l GNU/Linux

$ node -v
v4.2.1

$ npm -v
2.14.7

NPM debug log attached

[npm-debug.txt](https://github.com/victorporof/MAX7219.js/files/95263/npm-debug.txt)

Later ...
I found that I could run:

$ npm install spi

which installed 0.2.0 of SPI

This however was not compatible with max7219 which wants ~0.1.0

I downloaded the max7219 package and manually changed the dependency to ~0.2.0 and all now appears to work once installed.

I think we need to look at "freshening" this package to later code levels.

**Comment by victorporof** [comment]
Feel free to contribute! I'm not actively working on this project.

**Comment by nkolban** [comment]
Made the change and issued a pull request.
